### PR TITLE
Rewrite forward pass

### PR DESCRIPTION
**Pull request by jcrudy**
This includes:

1. More stable orthonormal updates based on householder reflections using lapack (current master uses Gram-Schmidt)
2. Support for arbitrary weights (no longer requires separable weight matrix)
3. Some new examples
4. A new `verbose` option that causes progress information to be printed during fitting
5. Improved handling of missingness and `max_degree`, which I think was buggy before
6. Improved readability of code, particularly for the forward pass
7. Changed fast MARS slightly - now it does one exhaustive search at the end when it runs out of candidates, and may continue thereafter with more fast MARS.  Perhaps this should be optional?
8. Some code for correcting numerical instability in knot search, which still could use a bit of analysis.  See https://github.com/scikit-learn-contrib/py-earth/blob/rewrite_forward_pass/pyearth/_knot_search.pyx#L585
9. I'm not sure whether this is faster or slower than the current master branch

@mehdidc Would like approval from you before merging if you have time.  Mostly, do you see any major problems or reasons not to merge this into master?  I want to include it in 0.1, so it seems good to get it into master so people will start using it and finding bugs as soon as possible.  I've been using this branch in my own work for a while, so I'm pretty confident in it.  However, you may see problems I don't.

### CODE REVIEW

**Comment by mehdidc** [comment]
Wow Great !  Sure I will try to review your code, I will tell you if I have any remark.

**Comment by mehdidc** [comment]
@jcrudy just to tell you I am still reviewing and testing your code, it is all working fine for now, and the verbose mode is really useful !
I tried to catch the numerical problem in the fast update function without success for now. 

And so about the numerical problem, if I understand well the code, when the numerical problem happens the knot is ignored, alpha and beta are refreshed (so that the error don't propagate), and we go to the next knot ? This looks like a reasonable solution to me, perhaps it should just appear in the verbose mode (probably a higher verbose level than the default one)

also, I ran fast.py in benchmarks/ and it seems that it now it is slower than 'normal' MARS,
I will try to investigate yet the part you modified, the output of fast.py I get is :

"diagnostic : MSE goes from 0.00156 to 0.00163 but it is 0.27x faster"

with the master it was:

"diagnostic : MSE goes from 0.00278 to 0.01566 but it is 35.98x faster"

**Comment by jcrudy** [comment]
@mehdidc Good catch on the fast mars thing.  I'm having a look now.  It's definitely the exhaustive search I added at the end that's the problem.  I'll either remove it or make it an option.  Just hacking out the relevant bits of code to disable the exhaustive search, I get this:

new version:
Normal : MSE=0.00156, duration=3.19s
Fast: MSE=0.01377, duration=2.67s
diagnostic : MSE goes from 0.00156 to 0.01377 but it is 1.20x faster

old version:
Normal : MSE=0.00278, duration=6.97s
Fast: MSE=0.01566, duration=0.18s
diagnostic : MSE goes from 0.00278 to 0.01566 but it is 39.01x faster

However, if I increase nb_examples from 400 to 4000 I get:

new version:
Normal : MSE=0.00200, duration=31.23s
Fast: MSE=0.00766, duration=1.45s
diagnostic : MSE goes from 0.00200 to 0.00766 but it is 21.48x faster

old version:
Normal : MSE=0.00211, duration=39.15s
Fast: MSE=0.00820, duration=1.48s
diagnostic : MSE goes from 0.00211 to 0.00820 but it is 26.46x faster

So I think it's working properly with exhaustive search removed, but the timing characteristics of the various parts of the code just changed somewhat.  I'll push an update to this PR soon with exhaustive search fixed.

**Comment by jcrudy** [comment]
@mehdidc I think I've fixed the fast MARS problem you found.  I'm going to change `verbose` from boolean to integer valued, and make it print out numerical problems when `verbose>=2` as you suggested.  After that, I think it would be good to merge into master, unless you've found anything else or want more time.

**Comment by mehdidc** [comment]
Great, looks good to me for a merge ! 

are your two last commits (8da3790 and 9be6c3e) related to this error
occurring in test_pickle_compatibility and test_copy_compatibility (only in Windows) ?

I added some benchmarks to check 9. 
In each  plot one parameter is varied, the others are fixed to some default value and training time is measured for the master and for your PR.
What I vary is : number of examples, number of variables, number of outputs, number of terms.

1)Without missingness:

1.1. Number of examples
 

1.2. Number of variables 



1.3.Number of outputs

 

1.4.Number of terms



2) With missingness:

2.1.Number of examples



2.2. Number of variables
 


2.3. Number of outputs



2.4. Number of terms



Source code is available here :https://gist.github.com/mehdidc/a8fe1758629f6f9125acb9883d895792#file-pyearth_benchmark_old_vs_new-py.

It seems that the new version is consistently slower than the master, but I guess
this should be investigated after merging this PR to master, what do you think ?

**Comment by jcrudy** [comment]
@mehdidc Wow, awesome work on the timings!  Yes, I agree.  Let's merge and then work on speed.  I'm sure there's plenty of opportunity for speed improvements.  I've never spent too much time on it, but I do know that the R package earth (written in C) is significantly faster than py-earth ever has been.

The last three commits were to address a problem with integer types that was happening on the 64 bit windows builds.  The problem is fixed now.  It was causing a bunch of the tests to fail, not just the pickle/copy compatibility tests.  I still don't know why those tests are failing in windows.

**Pull request merged**
